baseURL: "http://www.alexandertechnique.nl/"
defaultContentLanguage: "nl"
title: "Alexander Techniek Opleiding Nederland"
theme: "hyde"
sectionPagesMenu: "main"
canonifyurls: false
languages:
  nl:
    contentDir: content/dutch
    languageName: Lees in het Nederlands
    weight: 10
  en:
    contentDir: content/english
    languageName: Read in English
    weight: 20

params:
  author: "A. J. Hoorweg"
  description: "Teacher’s training for aspiring Alexander Technique-instructors. Amsterdam-area, Netherlands"
